// A list of currencies available on this site
const currencies = {
  USD: {
    code: "USD",
    symbol: "$",
    name: "US Dollar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "US dollars",
    "symbolNative": "$",
  },
  CAD: {
    code: "CAD",
    symbol: "CA$",
    name: "Canadian Dollar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Canadian dollars",
    "symbolNative": "$",
  },
  EUR: {
    code: "EUR",
    symbol: "€",
    name: "Euro",
    symbolPosition: "after",
    default: true,
    formatOptions: {
      symbol: "€",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "euros",
    "symbolNative": "€",
  },
  AED: {
    code: "AED",
    symbol: "AED",
    name: "United Arab Emirates Dirham",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "د",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "UAE dirhams",
    "symbolNative": "د.إ",
  },
  AFN: {
    code: "AFN",
    symbol: "Af",
    name: "Afghan Afghani",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "؋",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Afghan Afghanis",
    "symbolNative": "؋",
  },
  ALL: {
    code: "ALL",
    symbol: "ALL",
    name: "Albanian Lek",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "L",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Albanian lekë",
    "symbolNative": "Lek",
  },
  AMD: {
    code: "AMD",
    symbol: "AMD",
    name: "Armenian Dram",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "դ",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Armenian drams",
    "symbolNative": "դր.",
  },
  ARS: {
    code: "ARS",
    symbol: "AR$",
    name: "Argentine Peso",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Argentine pesos",
    "symbolNative": "$",
  },
  AUD: {
    code: "AUD",
    symbol: "AU$",
    name: "Australian Dollar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Australian dollars",
    "symbolNative": "$",
  },
  AZN: {
    code: "AZN",
    symbol: "man.",
    name: "Azerbaijani Manat",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "м",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Azerbaijani manats",
    "symbolNative": "ман",
  },
  BAM: {
    code: "BAM",
    symbol: "KM",
    name: "Bosnia-Herzegovina Convertible Mark",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "K",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Bosnia-Herzegovina convertible marks",
    "symbolNative": "KM",
  },
  BDT: {
    code: "BDT",
    symbol: "Tk",
    name: "Bangladeshi Taka",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "৳",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Bangladeshi takas",
    "symbolNative": "৳",
  },
  BGN: {
    code: "BGN",
    symbol: "BGN",
    name: "Bulgarian Lev",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "л",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Bulgarian leva",
    "symbolNative": "лв.",
  },
  BHD: {
    code: "BHD",
    symbol: "BD",
    name: "Bahraini Dinar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "د",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 3,
    "rounding": 0,
    "namePlural": "Bahraini dinars",
    "symbolNative": "د.ب",
  },
  BIF: {
    code: "BIF",
    symbol: "FBu",
    name: "Burundian Franc",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "F",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Burundian francs",
    "symbolNative": "FBu",
  },
  BND: {
    code: "BND",
    symbol: "BN$",
    name: "Brunei Dollar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Brunei dollars",
    "symbolNative": "$",
  },
  BOB: {
    code: "BOB",
    symbol: "Bs",
    name: "Bolivian Boliviano",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "B",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Bolivian bolivianos",
    "symbolNative": "Bs",
  },
  BRL: {
    code: "BRL",
    symbol: "R$",
    name: "Brazilian Real",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "R",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Brazilian reals",
    "symbolNative": "R$",
  },
  BWP: {
    code: "BWP",
    symbol: "BWP",
    name: "Botswanan Pula",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "P",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Botswanan pulas",
    "symbolNative": "P",
  },
  BYN: {
    code: "BYN",
    symbol: "Br",
    name: "Belarusian Ruble",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "р",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Belarusian rubles",
    "symbolNative": "руб",
  },
  BZD: {
    code: "BZD",
    symbol: "BZ$",
    name: "Belize Dollar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Belize dollars",
    "symbolNative": "$",
  },
  CDF: {
    code: "CDF",
    symbol: "CDF",
    name: "Congolese Franc",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "F",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Congolese francs",
    "symbolNative": "FrC",
  },
  CHF: {
    code: "CHF",
    symbol: "CHF",
    name: "Swiss Franc",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "C",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0.05,
    "namePlural": "Swiss francs",
    "symbolNative": "CHF",
  },
  CLP: {
    code: "CLP",
    symbol: "CL$",
    name: "Chilean Peso",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Chilean pesos",
    "symbolNative": "$",
  },
  CNY: {
    code: "CNY",
    symbol: "CN¥",
    name: "Chinese Yuan",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "C",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Chinese yuan",
    "symbolNative": "CN¥",
  },
  COP: {
    code: "COP",
    symbol: "CO$",
    name: "Colombian Peso",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Colombian pesos",
    "symbolNative": "$",
  },
  CRC: {
    code: "CRC",
    symbol: "₡",
    name: "Costa Rican Colón",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "₡",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Costa Rican colóns",
    "symbolNative": "₡",
  },
  CVE: {
    code: "CVE",
    symbol: "CV$",
    name: "Cape Verdean Escudo",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "C",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Cape Verdean escudos",
    "symbolNative": "CV$",
  },
  CZK: {
    code: "CZK",
    symbol: "Kč",
    name: "Czech Republic Koruna",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "K",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Czech Republic korunas",
    "symbolNative": "Kč",
  },
  DJF: {
    code: "DJF",
    symbol: "Fdj",
    name: "Djiboutian Franc",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "F",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Djiboutian francs",
    "symbolNative": "Fdj",
  },
  DKK: {
    code: "DKK",
    symbol: "kr",
    name: "Danish Krone",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "k",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Danish kroner",
    "symbolNative": "kr",
  },
  DOP: {
    code: "DOP",
    symbol: "RD$",
    name: "Dominican Peso",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "R",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Dominican pesos",
    "symbolNative": "RD$",
  },
  DZD: {
    code: "DZD",
    symbol: "DA",
    name: "Algerian Dinar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "د",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Algerian dinars",
    "symbolNative": "د.ج",
  },
  EGP: {
    code: "EGP",
    symbol: "EGP",
    name: "Egyptian Pound",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "ج",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Egyptian pounds",
    "symbolNative": "ج.م",
  },
  ERN: {
    code: "ERN",
    symbol: "Nfk",
    name: "Eritrean Nakfa",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "N",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Eritrean nakfas",
    "symbolNative": "Nfk",
  },
  ETB: {
    code: "ETB",
    symbol: "Br",
    name: "Ethiopian Birr",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "B",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Ethiopian birrs",
    "symbolNative": "Br",
  },
  GBP: {
    code: "GBP",
    symbol: "£",
    name: "British Pound Sterling",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "£",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "British pounds sterling",
    "symbolNative": "£",
  },
  GEL: {
    code: "GEL",
    symbol: "GEL",
    name: "Georgian Lari",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "G",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Georgian laris",
    "symbolNative": "GEL",
  },
  GHS: {
    code: "GHS",
    symbol: "GH₵",
    name: "Ghanaian Cedi",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "G",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Ghanaian cedis",
    "symbolNative": "GH₵",
  },
  GNF: {
    code: "GNF",
    symbol: "FG",
    name: "Guinean Franc",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "F",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Guinean francs",
    "symbolNative": "FG",
  },
  GTQ: {
    code: "GTQ",
    symbol: "GTQ",
    name: "Guatemalan Quetzal",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "Q",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Guatemalan quetzals",
    "symbolNative": "Q",
  },
  HKD: {
    code: "HKD",
    symbol: "HK$",
    name: "Hong Kong Dollar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Hong Kong dollars",
    "symbolNative": "$",
  },
  HNL: {
    code: "HNL",
    symbol: "HNL",
    name: "Honduran Lempira",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "L",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Honduran lempiras",
    "symbolNative": "L",
  },
  HRK: {
    code: "HRK",
    symbol: "kn",
    name: "Croatian Kuna",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "k",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Croatian kunas",
    "symbolNative": "kn",
  },
  HUF: {
    code: "HUF",
    symbol: "Ft",
    name: "Hungarian Forint",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "F",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Hungarian forints",
    "symbolNative": "Ft",
  },
  IDR: {
    code: "IDR",
    symbol: "Rp",
    name: "Indonesian Rupiah",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "R",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Indonesian rupiahs",
    "symbolNative": "Rp",
  },
  ILS: {
    code: "ILS",
    symbol: "₪",
    name: "Israeli New Sheqel",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "₪",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Israeli new sheqels",
    "symbolNative": "₪",
  },
  INR: {
    code: "INR",
    symbol: "Rs",
    name: "Indian Rupee",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "ট",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Indian rupees",
    "symbolNative": "টকা",
  },
  IQD: {
    code: "IQD",
    symbol: "IQD",
    name: "Iraqi Dinar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "د",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Iraqi dinars",
    "symbolNative": "د.ع",
  },
  IRR: {
    code: "IRR",
    symbol: "IRR",
    name: "Iranian Rial",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "﷼",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Iranian rials",
    "symbolNative": "﷼",
  },
  ISK: {
    code: "ISK",
    symbol: "Ikr",
    name: "Icelandic Króna",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "k",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Icelandic krónur",
    "symbolNative": "kr",
  },
  JMD: {
    code: "JMD",
    symbol: "J$",
    name: "Jamaican Dollar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Jamaican dollars",
    "symbolNative": "$",
  },
  JOD: {
    code: "JOD",
    symbol: "JD",
    name: "Jordanian Dinar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "د",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 3,
    "rounding": 0,
    "namePlural": "Jordanian dinars",
    "symbolNative": "د.أ",
  },
  JPY: {
    code: "JPY",
    symbol: "¥",
    name: "Japanese Yen",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "￥",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Japanese yen",
    "symbolNative": "￥",
  },
  KES: {
    code: "KES",
    symbol: "Ksh",
    name: "Kenyan Shilling",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "K",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Kenyan shillings",
    "symbolNative": "Ksh",
  },
  KHR: {
    code: "KHR",
    symbol: "KHR",
    name: "Cambodian Riel",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "៛",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Cambodian riels",
    "symbolNative": "៛",
  },
  KMF: {
    code: "KMF",
    symbol: "CF",
    name: "Comorian Franc",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "F",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Comorian francs",
    "symbolNative": "FC",
  },
  KRW: {
    code: "KRW",
    symbol: "₩",
    name: "South Korean Won",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "₩",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "South Korean won",
    "symbolNative": "₩",
  },
  KWD: {
    code: "KWD",
    symbol: "KD",
    name: "Kuwaiti Dinar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "د",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 3,
    "rounding": 0,
    "namePlural": "Kuwaiti dinars",
    "symbolNative": "د.ك",
  },
  KZT: {
    code: "KZT",
    symbol: "KZT",
    name: "Kazakhstani Tenge",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "т",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Kazakhstani tenges",
    "symbolNative": "тңг",
  },
  LBP: {
    code: "LBP",
    symbol: "LB£",
    name: "Lebanese Pound",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "ل",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Lebanese pounds",
    "symbolNative": "ل.ل",
  },
  LKR: {
    code: "LKR",
    symbol: "SLRs",
    name: "Sri Lankan Rupee",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "S",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Sri Lankan rupees",
    "symbolNative": "SL ",
  },
  LYD: {
    code: "LYD",
    symbol: "LD",
    name: "Libyan Dinar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "د",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 3,
    "rounding": 0,
    "namePlural": "Libyan dinars",
    "symbolNative": "د.ل",
  },
  MAD: {
    code: "MAD",
    symbol: "MAD",
    name: "Moroccan Dirham",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "د",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Moroccan dirhams",
    "symbolNative": "د.م",
  },
  MDL: {
    code: "MDL",
    symbol: "MDL",
    name: "Moldovan Leu",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "M",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Moldovan lei",
    "symbolNative": "MDL",
  },
  MGA: {
    code: "MGA",
    symbol: "MGA",
    name: "Malagasy Ariary",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "M",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Malagasy Ariaries",
    "symbolNative": "MGA",
  },
  MKD: {
    code: "MKD",
    symbol: "MKD",
    name: "Macedonian Denar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "M",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Macedonian denari",
    "symbolNative": "MKD",
  },
  MMK: {
    code: "MMK",
    symbol: "MMK",
    name: "Myanma Kyat",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "K",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Myanma kyats",
    "symbolNative": "K",
  },
  MOP: {
    code: "MOP",
    symbol: "MOP$",
    name: "Macanese Pataca",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "M",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Macanese patacas",
    "symbolNative": "MOP",
  },
  MUR: {
    code: "MUR",
    symbol: "MURs",
    name: "Mauritian Rupee",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "M",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Mauritian rupees",
    "symbolNative": "MUR",
  },
  MXN: {
    code: "MXN",
    symbol: "MX$",
    name: "Mexican Peso",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Mexican pesos",
    "symbolNative": "$",
  },
  MYR: {
    code: "MYR",
    symbol: "RM",
    name: "Malaysian Ringgit",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "R",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Malaysian ringgits",
    "symbolNative": "RM",
  },
  MZN: {
    code: "MZN",
    symbol: "MTn",
    name: "Mozambican Metical",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "M",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Mozambican meticals",
    "symbolNative": "MTn",
  },
  NAD: {
    code: "NAD",
    symbol: "N$",
    name: "Namibian Dollar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "N",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Namibian dollars",
    "symbolNative": "N$",
  },
  NGN: {
    code: "NGN",
    symbol: "₦",
    name: "Nigerian Naira",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "₦",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Nigerian nairas",
    "symbolNative": "₦",
  },
  NIO: {
    code: "NIO",
    symbol: "C$",
    name: "Nicaraguan Córdoba",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "C",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Nicaraguan córdobas",
    "symbolNative": "C$",
  },
  NOK: {
    code: "NOK",
    symbol: "Nkr",
    name: "Norwegian Krone",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "k",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Norwegian kroner",
    "symbolNative": "kr",
  },
  NPR: {
    code: "NPR",
    symbol: "NPRs",
    name: "Nepalese Rupee",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "ने",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Nepalese rupees",
    "symbolNative": "नेरू",
  },
  NZD: {
    code: "NZD",
    symbol: "NZ$",
    name: "New Zealand Dollar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "New Zealand dollars",
    "symbolNative": "$",
  },
  OMR: {
    code: "OMR",
    symbol: "OMR",
    name: "Omani Rial",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "ر",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 3,
    "rounding": 0,
    "namePlural": "Omani rials",
    "symbolNative": "ر.ع",
  },
  PAB: {
    code: "PAB",
    symbol: "B/.",
    name: "Panamanian Balboa",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "B",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Panamanian balboas",
    "symbolNative": "B/.",
  },
  PEN: {
    code: "PEN",
    symbol: "S/.",
    name: "Peruvian Nuevo Sol",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "S",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Peruvian nuevos soles",
    "symbolNative": "S/.",
  },
  PHP: {
    code: "PHP",
    symbol: "₱",
    name: "Philippine Peso",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "₱",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Philippine pesos",
    "symbolNative": "₱",
  },
  PKR: {
    code: "PKR",
    symbol: "PKRs",
    name: "Pakistani Rupee",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "₨",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Pakistani rupees",
    "symbolNative": "₨",
  },
  PLN: {
    code: "PLN",
    symbol: "zł",
    name: "Polish Zloty",
    symbolPosition: "after",
    default: false,
    formatOptions: {
      symbol: "z",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Polish zlotys",
    "symbolNative": "zł",
  },
  PYG: {
    code: "PYG",
    symbol: "₲",
    name: "Paraguayan Guarani",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "₲",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Paraguayan guaranis",
    "symbolNative": "₲",
  },
  QAR: {
    code: "QAR",
    symbol: "QR",
    name: "Qatari Rial",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "ر",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Qatari rials",
    "symbolNative": "ر.ق",
  },
  RON: {
    code: "RON",
    symbol: "RON",
    name: "Romanian Leu",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "R",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Romanian lei",
    "symbolNative": "RON",
  },
  RSD: {
    code: "RSD",
    symbol: "din.",
    name: "Serbian Dinar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "д",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Serbian dinars",
    "symbolNative": "дин",
  },
  RUB: {
    code: "RUB",
    symbol: "RUB",
    name: "Russian Ruble",
    symbolPosition: "after",
    default: false,
    formatOptions: {
      symbol: "₽",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Russian rubles",
    "symbolNative": "₽.",
  },
  RWF: {
    code: "RWF",
    symbol: "RWF",
    name: "Rwandan Franc",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "F",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Rwandan francs",
    "symbolNative": "FR",
  },
  SAR: {
    code: "SAR",
    symbol: "SR",
    name: "Saudi Riyal",
    symbolPosition: "after",
    default: false,
    formatOptions: {
      symbol: "ر",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Saudi riyals",
    "symbolNative": "ر.س",
  },
  SDG: {
    code: "SDG",
    symbol: "SDG",
    name: "Sudanese Pound",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "S",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Sudanese pounds",
    "symbolNative": "SDG",
  },
  SEK: {
    code: "SEK",
    symbol: "kr",
    name: "Swedish Krona",
    symbolPosition: "after",
    default: false,
    formatOptions: {
      symbol: "kr",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Swedish kronor",
    "symbolNative": "kr",
  },
  SGD: {
    code: "SGD",
    symbol: "S$",
    name: "Singapore Dollar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Singapore dollars",
    "symbolNative": "$",
  },
  SOS: {
    code: "SOS",
    symbol: "Ssh",
    name: "Somali Shilling",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "S",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Somali shillings",
    "symbolNative": "Ssh",
  },
  SYP: {
    code: "SYP",
    symbol: "SY£",
    name: "Syrian Pound",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "ل",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Syrian pounds",
    "symbolNative": "ل.س",
  },
  THB: {
    code: "THB",
    symbol: "฿",
    name: "Thai Baht",
    symbolPosition: "after",
    default: false,
    formatOptions: {
      symbol: "฿",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Thai baht",
    "symbolNative": "฿",
  },
  TND: {
    code: "TND",
    symbol: "DT",
    name: "Tunisian Dinar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "د",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 3,
    "rounding": 0,
    "namePlural": "Tunisian dinars",
    "symbolNative": "د.ت",
  },
  TOP: {
    code: "TOP",
    symbol: "T$",
    name: "Tongan Paʻanga",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "T",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Tongan paʻanga",
    "symbolNative": "T$",
  },
  TRY: {
    code: "TRY",
    symbol: "TL",
    name: "Turkish Lira",
    symbolPosition: "after",
    default: false,
    formatOptions: {
      symbol: "T",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Turkish Lira",
    "symbolNative": "TL",
  },
  TTD: {
    code: "TTD",
    symbol: "TT$",
    name: "Trinidad and Tobago Dollar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Trinidad and Tobago dollars",
    "symbolNative": "$",
  },
  TWD: {
    code: "TWD",
    symbol: "NT$",
    name: "New Taiwan Dollar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "N",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "New Taiwan dollars",
    "symbolNative": "NT$",
  },
  TZS: {
    code: "TZS",
    symbol: "TSh",
    name: "Tanzanian Shilling",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "T",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Tanzanian shillings",
    "symbolNative": "TSh",
  },
  UAH: {
    code: "UAH",
    symbol: "₴",
    name: "Ukrainian Hryvnia",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "₴",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Ukrainian hryvnias",
    "symbolNative": "₴",
  },
  UGX: {
    code: "UGX",
    symbol: "USh",
    name: "Ugandan Shilling",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "U",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Ugandan shillings",
    "symbolNative": "USh",
  },
  UYU: {
    code: "UYU",
    symbol: "$U",
    name: "Uruguayan Peso",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "$",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Uruguayan pesos",
    "symbolNative": "$",
  },
  UZS: {
    code: "UZS",
    symbol: "UZS",
    name: "Uzbekistan Som",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "U",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Uzbekistan som",
    "symbolNative": "UZS",
  },
  VEF: {
    code: "VES",
    symbol: "Bs.F.",
    name: "Venezuelan Bolívar",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "B",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "Venezuelan bolívars",
    "symbolNative": "Bs.",
  },
  VND: {
    code: "VND",
    symbol: "₫",
    name: "Vietnamese Dong",
    symbolPosition: "after",
    default: false,
    formatOptions: {
      symbol: "₫",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Vietnamese dong",
    "symbolNative": "₫",
  },
  XAF: {
    code: "XAF",
    symbol: "FCFA",
    name: "CFA Franc BEAC",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "F",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "CFA francs BEAC",
    "symbolNative": "FCF",
  },
  XOF: {
    code: "XOF",
    symbol: "CFA",
    name: "CFA Franc BCEAO",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "C",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "CFA francs BCEAO",
    "symbolNative": "CFA",
  },
  YER: {
    code: "YER",
    symbol: "YR",
    name: "Yemeni Rial",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "ر",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Yemeni rials",
    "symbolNative": "ر.ي",
  },
  ZAR: {
    code: "ZAR",
    symbol: "R",
    name: "South African Rand",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "R",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 2,
    "rounding": 0,
    "namePlural": "South African rand",
    "symbolNative": "R",
  },
  ZMK: {
    code: "ZMW",
    symbol: "ZK",
    name: "Zambian Kwacha",
    symbolPosition: "before",
    default: false,
    formatOptions: {
      symbol: "Z",
      pattern: "# !",
      precision: 2,
    },
    "decimalDigits": 0,
    "rounding": 0,
    "namePlural": "Zambian kwachas",
    "symbolNative": "ZK",
  }
}
